name: Assignment8 Tests

on:
  push:
    branches:
      - main
    paths:
      - 'Assignment8/**'
      - '.github/workflows/assignment8-tests.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Assignment8/**'
      - '.github/workflows/assignment8-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'   # matches your installed version

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with pytest and enforce 100% coverage
        run: |
          pytest Assignment8/tests --cov=Assignment8/app --cov-fail-under=100

          